# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import api_pb2 as api__pb2


class ServerApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/protobuf.ServerApi/register',
        request_serializer=api__pb2.RegisterMessage.SerializeToString,
        response_deserializer=api__pb2.SimpleResp.FromString,
        )
    self.ping = channel.unary_unary(
        '/protobuf.ServerApi/ping',
        request_serializer=api__pb2.HbMessage.SerializeToString,
        response_deserializer=api__pb2.SimpleResp.FromString,
        )
    self.upload_metrics = channel.unary_unary(
        '/protobuf.ServerApi/upload_metrics',
        request_serializer=api__pb2.MetricsMessage.SerializeToString,
        response_deserializer=api__pb2.SimpleResp.FromString,
        )
    self.api_upload_metrics = channel.unary_unary(
        '/protobuf.ServerApi/api_upload_metrics',
        request_serializer=api__pb2.ApiMetricsMessage.SerializeToString,
        response_deserializer=api__pb2.SimpleResp.FromString,
        )
    self.get_init_config = channel.unary_unary(
        '/protobuf.ServerApi/get_init_config',
        request_serializer=api__pb2.SimpleMessage.SerializeToString,
        response_deserializer=api__pb2.InitConfigResp.FromString,
        )
    self.upload_download_result = channel.unary_unary(
        '/protobuf.ServerApi/upload_download_result',
        request_serializer=api__pb2.PluginDownloadResult.SerializeToString,
        response_deserializer=api__pb2.SimpleResp.FromString,
        )


class ServerApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload_metrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def api_upload_metrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_init_config(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload_download_result(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ServerApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=api__pb2.RegisterMessage.FromString,
          response_serializer=api__pb2.SimpleResp.SerializeToString,
      ),
      'ping': grpc.unary_unary_rpc_method_handler(
          servicer.ping,
          request_deserializer=api__pb2.HbMessage.FromString,
          response_serializer=api__pb2.SimpleResp.SerializeToString,
      ),
      'upload_metrics': grpc.unary_unary_rpc_method_handler(
          servicer.upload_metrics,
          request_deserializer=api__pb2.MetricsMessage.FromString,
          response_serializer=api__pb2.SimpleResp.SerializeToString,
      ),
      'api_upload_metrics': grpc.unary_unary_rpc_method_handler(
          servicer.api_upload_metrics,
          request_deserializer=api__pb2.ApiMetricsMessage.FromString,
          response_serializer=api__pb2.SimpleResp.SerializeToString,
      ),
      'get_init_config': grpc.unary_unary_rpc_method_handler(
          servicer.get_init_config,
          request_deserializer=api__pb2.SimpleMessage.FromString,
          response_serializer=api__pb2.InitConfigResp.SerializeToString,
      ),
      'upload_download_result': grpc.unary_unary_rpc_method_handler(
          servicer.upload_download_result,
          request_deserializer=api__pb2.PluginDownloadResult.FromString,
          response_serializer=api__pb2.SimpleResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'protobuf.ServerApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
