# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=_b('Z\010protobuf'),
  serialized_pb=_b('\n\tapi.proto\x12\x08protobuf\"9\n\x0fRegisterMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x14\n\x0cinstall_path\x18\x02 \x01(\t\"\\\n\x14PluginDownloadResult\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x11\n\tplugin_id\x18\x02 \x01(\x05\x12\x12\n\nis_success\x18\x03 \x01(\x08\x12\x0b\n\x03msg\x18\x04 \x01(\t\"\x1d\n\tHbMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\xab\x01\n\x0eMetricsMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x13\n\x0binstance_id\x18\x02 \x01(\t\x12\x15\n\rexecute_times\x18\x03 \x01(\x05\x12\x11\n\texit_code\x18\x04 \x01(\x05\x12\x0f\n\x07std_out\x18\x05 \x03(\t\x12\x0f\n\x07std_err\x18\x06 \x01(\t\x12\n\n\x02ts\x18\x07 \x01(\t\x12\x1a\n\x12raw_execute_result\x18\x08 \x01(\t\"U\n\x11\x41piMetricsMessage\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0f\n\x07metrics\x18\x02 \x03(\t\x12\x14\n\x0cservice_name\x18\x03 \x01(\t\x12\n\n\x02ts\x18\x04 \x01(\t\"!\n\rSimpleMessage\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\"\'\n\nSimpleResp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\"U\n\x0eInitConfigResp\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x13\n\x0bhb_interval\x18\x02 \x01(\x05\x12\x13\n\x0b\x63oncurrency\x18\x03 \x01(\x05\x12\x0b\n\x03msg\x18\x04 \x01(\t2\xa8\x03\n\tServerApi\x12=\n\x08register\x12\x19.protobuf.RegisterMessage\x1a\x14.protobuf.SimpleResp\"\x00\x12\x33\n\x04ping\x12\x13.protobuf.HbMessage\x1a\x14.protobuf.SimpleResp\"\x00\x12\x42\n\x0eupload_metrics\x12\x18.protobuf.MetricsMessage\x1a\x14.protobuf.SimpleResp\"\x00\x12I\n\x12\x61pi_upload_metrics\x12\x1b.protobuf.ApiMetricsMessage\x1a\x14.protobuf.SimpleResp\"\x00\x12\x46\n\x0fget_init_config\x12\x17.protobuf.SimpleMessage\x1a\x18.protobuf.InitConfigResp\"\x00\x12P\n\x16upload_download_result\x12\x1e.protobuf.PluginDownloadResult\x1a\x14.protobuf.SimpleResp\"\x00\x42\nZ\x08protobufb\x06proto3')
)




_REGISTERMESSAGE = _descriptor.Descriptor(
  name='RegisterMessage',
  full_name='protobuf.RegisterMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='protobuf.RegisterMessage.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='install_path', full_name='protobuf.RegisterMessage.install_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=80,
)


_PLUGINDOWNLOADRESULT = _descriptor.Descriptor(
  name='PluginDownloadResult',
  full_name='protobuf.PluginDownloadResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='protobuf.PluginDownloadResult.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='plugin_id', full_name='protobuf.PluginDownloadResult.plugin_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_success', full_name='protobuf.PluginDownloadResult.is_success', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.PluginDownloadResult.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=174,
)


_HBMESSAGE = _descriptor.Descriptor(
  name='HbMessage',
  full_name='protobuf.HbMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='protobuf.HbMessage.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=205,
)


_METRICSMESSAGE = _descriptor.Descriptor(
  name='MetricsMessage',
  full_name='protobuf.MetricsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='protobuf.MetricsMessage.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='instance_id', full_name='protobuf.MetricsMessage.instance_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='execute_times', full_name='protobuf.MetricsMessage.execute_times', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exit_code', full_name='protobuf.MetricsMessage.exit_code', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std_out', full_name='protobuf.MetricsMessage.std_out', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='std_err', full_name='protobuf.MetricsMessage.std_err', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='protobuf.MetricsMessage.ts', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='raw_execute_result', full_name='protobuf.MetricsMessage.raw_execute_result', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=379,
)


_APIMETRICSMESSAGE = _descriptor.Descriptor(
  name='ApiMetricsMessage',
  full_name='protobuf.ApiMetricsMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='token', full_name='protobuf.ApiMetricsMessage.token', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metrics', full_name='protobuf.ApiMetricsMessage.metrics', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='service_name', full_name='protobuf.ApiMetricsMessage.service_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='protobuf.ApiMetricsMessage.ts', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=381,
  serialized_end=466,
)


_SIMPLEMESSAGE = _descriptor.Descriptor(
  name='SimpleMessage',
  full_name='protobuf.SimpleMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_id', full_name='protobuf.SimpleMessage.agent_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=468,
  serialized_end=501,
)


_SIMPLERESP = _descriptor.Descriptor(
  name='SimpleResp',
  full_name='protobuf.SimpleResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protobuf.SimpleResp.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.SimpleResp.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=503,
  serialized_end=542,
)


_INITCONFIGRESP = _descriptor.Descriptor(
  name='InitConfigResp',
  full_name='protobuf.InitConfigResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protobuf.InitConfigResp.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hb_interval', full_name='protobuf.InitConfigResp.hb_interval', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='concurrency', full_name='protobuf.InitConfigResp.concurrency', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.InitConfigResp.msg', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=629,
)

DESCRIPTOR.message_types_by_name['RegisterMessage'] = _REGISTERMESSAGE
DESCRIPTOR.message_types_by_name['PluginDownloadResult'] = _PLUGINDOWNLOADRESULT
DESCRIPTOR.message_types_by_name['HbMessage'] = _HBMESSAGE
DESCRIPTOR.message_types_by_name['MetricsMessage'] = _METRICSMESSAGE
DESCRIPTOR.message_types_by_name['ApiMetricsMessage'] = _APIMETRICSMESSAGE
DESCRIPTOR.message_types_by_name['SimpleMessage'] = _SIMPLEMESSAGE
DESCRIPTOR.message_types_by_name['SimpleResp'] = _SIMPLERESP
DESCRIPTOR.message_types_by_name['InitConfigResp'] = _INITCONFIGRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterMessage = _reflection.GeneratedProtocolMessageType('RegisterMessage', (_message.Message,), dict(
  DESCRIPTOR = _REGISTERMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.RegisterMessage)
  ))
_sym_db.RegisterMessage(RegisterMessage)

PluginDownloadResult = _reflection.GeneratedProtocolMessageType('PluginDownloadResult', (_message.Message,), dict(
  DESCRIPTOR = _PLUGINDOWNLOADRESULT,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.PluginDownloadResult)
  ))
_sym_db.RegisterMessage(PluginDownloadResult)

HbMessage = _reflection.GeneratedProtocolMessageType('HbMessage', (_message.Message,), dict(
  DESCRIPTOR = _HBMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.HbMessage)
  ))
_sym_db.RegisterMessage(HbMessage)

MetricsMessage = _reflection.GeneratedProtocolMessageType('MetricsMessage', (_message.Message,), dict(
  DESCRIPTOR = _METRICSMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MetricsMessage)
  ))
_sym_db.RegisterMessage(MetricsMessage)

ApiMetricsMessage = _reflection.GeneratedProtocolMessageType('ApiMetricsMessage', (_message.Message,), dict(
  DESCRIPTOR = _APIMETRICSMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.ApiMetricsMessage)
  ))
_sym_db.RegisterMessage(ApiMetricsMessage)

SimpleMessage = _reflection.GeneratedProtocolMessageType('SimpleMessage', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLEMESSAGE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SimpleMessage)
  ))
_sym_db.RegisterMessage(SimpleMessage)

SimpleResp = _reflection.GeneratedProtocolMessageType('SimpleResp', (_message.Message,), dict(
  DESCRIPTOR = _SIMPLERESP,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.SimpleResp)
  ))
_sym_db.RegisterMessage(SimpleResp)

InitConfigResp = _reflection.GeneratedProtocolMessageType('InitConfigResp', (_message.Message,), dict(
  DESCRIPTOR = _INITCONFIGRESP,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.InitConfigResp)
  ))
_sym_db.RegisterMessage(InitConfigResp)


DESCRIPTOR._options = None

_SERVERAPI = _descriptor.ServiceDescriptor(
  name='ServerApi',
  full_name='protobuf.ServerApi',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=632,
  serialized_end=1056,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='protobuf.ServerApi.register',
    index=0,
    containing_service=None,
    input_type=_REGISTERMESSAGE,
    output_type=_SIMPLERESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='protobuf.ServerApi.ping',
    index=1,
    containing_service=None,
    input_type=_HBMESSAGE,
    output_type=_SIMPLERESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_metrics',
    full_name='protobuf.ServerApi.upload_metrics',
    index=2,
    containing_service=None,
    input_type=_METRICSMESSAGE,
    output_type=_SIMPLERESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='api_upload_metrics',
    full_name='protobuf.ServerApi.api_upload_metrics',
    index=3,
    containing_service=None,
    input_type=_APIMETRICSMESSAGE,
    output_type=_SIMPLERESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='get_init_config',
    full_name='protobuf.ServerApi.get_init_config',
    index=4,
    containing_service=None,
    input_type=_SIMPLEMESSAGE,
    output_type=_INITCONFIGRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_download_result',
    full_name='protobuf.ServerApi.upload_download_result',
    index=5,
    containing_service=None,
    input_type=_PLUGINDOWNLOADRESULT,
    output_type=_SIMPLERESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVERAPI)

DESCRIPTOR.services_by_name['ServerApi'] = _SERVERAPI

# @@protoc_insertion_point(module_scope)
